# Generated by Django 5.1.5 on 2025-03-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
    ]
